services:
  restapi_app:    
    build: 
      target: runner 
      context: .
      dockerfile: Dockerfile   
    env_file:
      - "./.env"
    environment:
      - ENV=production
    volumes:
      - .:/restapi_mysql:rw
    ports:
      - 3000:3000
    depends_on:
      - restapi_db

  restapi_dbnosql:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Yaseer10@
    volumes:
      - db_mongodb:/data/db
      
  restapi_db: 
    image: mysql
    volumes:
           - db_mysql:/var/lib/mysql
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
       MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - restapi_db

volumes: 
  db_mysql:
  db_mongodb:
version: '3.9'